/**
 * Created by chalresbao on 16/11/24.
 */
const ActionType = {

    CLEAR:"CLEAR",

    STATE_ACTIONS:{

        SET_HOME_SECTION_INDEX:"SET_HOME_SECTION_INDEX",

        SET_USER_MISSION_INDEX:"USER_MISSION_INDEX",

        SET_FILTER_INDEX:"SET_FILTER_INDEX",

        SET_SEARCH_VALUE:"SET_SEARCH_VALUE",

        SET_CURRENT_USER_MISSION_INDEX:"SET_CURRENT_USER_MISSION_INDEX",

        SET_INIT_FETCH_MISSION:"SET_INIT_FETCH_MISSION",

        SET_MISSION_LIST_SCROLL_TOP:"SET_MISSION_LIST_SCROLL_TOP",

        SET_MISSION_SEARCH_SCROLL_TOP: "SET_MISSION_SEARCH_SCROLL_TOP",

        CLEAR:"CLEAR",
    },
    USER_ACTIONS:{
        //注册
        POST_USER_REGISTER:"POST_USER_REGISTER",
        //登陆
        POST_USER_LOGIN:"POST_USER_LOGIN",
        //获取用户任务
        QUERY_USER_MISSION:"QUERY_USER_MISSION",

        POST_USER_CHANGE_PHONE_NUMBER: "POST_USER_CHANGE_PHONE_NUMBER",

        POST_UPDATE_USER_INFO:"POST_UPDATE_USER_INFO",

        POST_REQUEST_VERIFY_NUMBER:"POST_REQUEST_VERIFY_NUMBER",

        POST_VERIFY_SMS_NUMBER:"POST_VERIFY_SMS_NUMBER",

        POST_UPDATE_USER_MISSION:"POST_UPDATE_USER_MISSION",

        SET_CURRENT_USER_MISSION_ID:"SET_CURRENT_USER_MISSION_ID",

        CLEAR:"CLEAR",
    },
    MISSION_ACTIONS:{
        //获取任务
        QUERY_MISSIONS:"QUERY_MISSIONS",
        //搜索任务
        QUERY_MISSION_BY_SEARCH:"QUERY_MISSION_BY_SEARCH",

        QUERY_CURRENT_MISSION_COMMENTS:"QUERY_CURRENT_MISSION_COMMENTS",

        QUERY_RELATED_MISSIONS:"QUERY_RELATED_MISSIONS",

        SET_CURRENT_MISSION:"SET_CURRENT_MISSION",

        SET_MISSIONS:"SET_MISSIONS",

        SET_LOADED_MISSION_SEARCH_PAGE:"SET_LOADED_MISSION_SEARCH_PAGE",

        SET_MISSION_LIST_SCROLL_TOP:"SET_MISSION_LIST_SCROLL_TOP",

        CLEAR:"CLEAR",
    }
};

export default ActionType;