/**
 * Created by chalresbao on 16/11/24.
 */
const ActionType = {
    CLEAR:"CLEAR",
    STORAGE_ACTIONS:{
        SET_LOCAL_USER:"SET_USER",
        SET_LOCAL_MISSION_LIST:"SET_MISSION_LIST",
        CLEAR:"CLEAR",
    },
    STATE_ACTIONS:{
        SET_HOME_SECTION_INDEX:"SET_HOME_SECTION_INDEX",
        SET_USER_MISSION_INDEX:"USER_MISSION_INDEX",
        SET_FILTER_INDEX:"SET_FILTER_INDEX",
        SET_SEARCH_VALUE:"SET_SEARCH_VALUE",
        SET_CURRENT_USER_MISSION_INDEX:"SET_CURRENT_USER_MISSION_INDEX",
        SET_INIT_FETCH_MISSION:"SET_INIT_FETCH_MISSION",
        SET_MISSION_LIST_SCROLL_TOP:"SET_MISSION_LIST_SCROLL_TOP",
        CLEAR:"CLEAR",
    },
    USER_ACTIONS:{
        //注册
        POST_USER_REGISTER:"POST_USER_REGISTER",
        //登陆
        POST_USER_LOGIN:"POST_USER_LOGIN",
        //登出
        POST_USER_LOGOUT:"POST_USER_LOGOUT",
        //更换头像
        POST_USER_CHANGE_AVATAR:"POST_USER_CHANGE_AVATAR",
        //更改昵称
        POST_USER_CHANGE_NICKNAME:"POST_USER_CHANGE_NICKNAME",
        //修改密码
        POST_USER_CHANGE_PASSWORD:"POST_USER_CHANGE_PASSWORD",
        //修改手机号
        POST_USER_CHANGE_PHONE_NUMBER:"POST_USER_CHANGE_PHONE_NUMBER",

        //开始任务
        POST_USER_MISSION_START:"POST_USER_MISSION_START",
        //提交任务
        POST_USER_MISSION_FINISH:"POST_USER_MISSION_FINISH",
        //收藏
        POST_USER_CHANGE_FAVOURITE_MISSION:"POST_USER_CHANGE_FAVOURITE_MISSION",
        //删除失效
        POST_USER_REMOVE_DESTROY_MISSION:"POST_USER_REMOVE_DESTROY_MISSION",

        //获取用户所有信息
        QUERY_USER:"QUERY_USER",
        //获取用户任务
        QUERY_USER_MISSION:"QUERY_USER_MISSION",
        //获取用户个人信息
        QUERY_USER_INFORMATION:"QUERY_USER_INFORMATION",

        QUERY_CURRENT_MISSION_DETAIL:"QUERY_CURRENT_MISSION_DETAIL",

        QUERY_CURRENT_MISSION_FAVOUR:"QUERY_CURRENT_MISSION_FAVOUR",

        CHECK_USER_LOGIN:"CHECK_USER_LOGIN",
        POST_UPDATE_USER_INFO:"POST_UPDATE_USER_INFO",
        POST_REQUEST_VERIFY_NUMBER:"POST_REQUEST_VERIFY_NUMBER",
        POST_VERIFY_SMS_NUMBER:"POST_VERIFY_SMS_NUMBER",
        POST_UPDATE_USER_MISSION:"POST_UPDATE_USER_MISSION",
        SET_CURRENT_USER_MISSION_ID:"SET_CURRENT_USER_MISSION_ID",
        CLEAR:"CLEAR",
        USER_CLEAR:"USER_CLEAR"

    },
    MISSION_ACTIONS:{
        //获取最新Banner
        QUERY_NEW_BANNER:"QUERY_NEW_BANNER",
        //获取splashScreen广告
        QUERY_NEW_SPLASH_SCREEN:"QUERY_NEW_SPLASH_SCREEN",
        //获取任务
        QUERY_MISSION:"QUERY_MISSION",
        //搜索任务
        QUERY_MISSION_BY_SEARCH:"QUERY_MISSION_BY_SEARCH",

        QUERY_CURRENT_MISSION_COMMENTS:"QUERY_CURRENT_MISSION_COMMENTS",
        QUERY_MORE_MISSION:"QUERY_MORE_MISSION",
        QUERY_RELATED_MISSIONS:"QUERY_RELATED_MISSIONS",

        SET_CURRENT_MISSION:"SET_CURRENT_MISSION",

        SET_LOADED_MISSION_PAGE:"SET_LOADED_MISSION_PAGE",

        SET_MISSION_LIST_SCROLL_TOP:"SET_MISSION_LIST_SCROLL_TOP",

        CLEAR_CURRENT_RELATED_MISSIONS:"CLEAR_CURRENT_RELATED_MISSIONS",

        CLEAR:"CLEAR",
    }
};

export default ActionType;